sonar.projectKey=autocomplete-system-frontend
sonar.projectName=autocomplete-frontend

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/autocomplete-frontend/lcov.info

sonar.typescript.tsconfigPaths=tsconfig.json,tsconfig.spec.json

