server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: autocomplete-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      # если без docker, можно localhost

logging:
  level:
    root: INFO
    lt.satsyuk.autocomplete: DEBUG

autocomplete:
  redis-prefix: "${AUTOCOMPLETE_REDIS_PREFIX:autocomplete:}"

---
spring:
  config:
    activate:
      on-profile: strict
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:?SPRING_DATA_REDIS_HOST is required in strict profile}
      port: ${SPRING_DATA_REDIS_PORT:?SPRING_DATA_REDIS_PORT is required in strict profile}

