server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: cdc-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: cdc-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

logging:
  level:
    root: INFO
    lt.satsyuk.cdc: DEBUG

cdc:
  topic-pattern: '${CDC_TOPIC_PATTERN:db-changes\.public\.search_stats}'

autocomplete:
  redis-prefix: "${AUTOCOMPLETE_REDIS_PREFIX:autocomplete:}"
  clear-index-timeout: ${AUTOCOMPLETE_CLEAR_INDEX_TIMEOUT:PT5M}

---
spring:
  config:
    activate:
      on-profile: strict
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:?SPRING_KAFKA_BOOTSTRAP_SERVERS is required in strict profile}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:?SPRING_DATA_REDIS_HOST is required in strict profile}
      port: ${SPRING_DATA_REDIS_PORT:?SPRING_DATA_REDIS_PORT is required in strict profile}

